import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogClose } from './ui/dialog';
import { Button } from './ui/button';
import { HelpCircle } from 'lucide-react';
const SubscriptionHelpButton = () => {
    const [open, setOpen] = useState(false);
    return (_jsxs(Dialog, { open: open, onOpenChange: setOpen, children: [_jsx(DialogTrigger, { asChild: true, children: _jsx(Button, { variant: "ghost", size: "icon", className: "text-gray-500 hover:text-gray-700 rounded-full", "aria-label": "Informaci\u00F3n de suscripci\u00F3n", children: _jsx(HelpCircle, { className: "h-5 w-5" }) }) }), _jsxs(DialogContent, { className: "sm:max-w-md", children: [_jsx(DialogHeader, { children: _jsx(DialogTitle, { children: "Informaci\u00F3n de Suscripci\u00F3n" }) }), _jsxs("div", { className: "space-y-4", children: [_jsxs("section", { children: [_jsx("h3", { className: "text-lg font-medium text-blue-600", children: "Plan Mensual - 280Bs./Mensual" }), _jsx("p", { className: "text-sm text-gray-600 mt-1", children: "InventorySuit funciona con un modelo de suscripci\u00F3n mensual que te brinda acceso a todas las funcionalidades del sistema." })] }), _jsxs("section", { children: [_jsx("h4", { className: "font-medium mb-2", children: "Beneficios incluidos:" }), _jsxs("ul", { className: "list-disc pl-5 text-sm text-gray-600 space-y-1", children: [_jsx("li", { children: "Gesti\u00F3n completa de inventario" }), _jsx("li", { children: "Control de m\u00FAltiples almacenes" }), _jsx("li", { children: "Reportes detallados de ventas y compras" }), _jsx("li", { children: "Gesti\u00F3n de usuarios y permisos" }), _jsx("li", { children: "Exportaci\u00F3n de datos a CSV" }), _jsx("li", { children: "Soporte t\u00E9cnico prioritario" }), _jsx("li", { children: "Actualizaciones constantes" })] })] }), _jsxs("section", { children: [_jsx("h4", { className: "font-medium mb-2", children: "\u00BFC\u00F3mo funciona?" }), _jsxs("ol", { className: "list-decimal pl-5 text-sm text-gray-600 space-y-1", children: [_jsx("li", { children: "La suscripci\u00F3n tiene validez por 30 d\u00EDas" }), _jsx("li", { children: "Recibir\u00E1s notificaciones cuando est\u00E9 pr\u00F3xima a vencer" }), _jsx("li", { children: "Puedes renovar f\u00E1cilmente desde el panel principal" }), _jsx("li", { children: "Si vence, el sistema se bloquear\u00E1 hasta la renovaci\u00F3n" })] })] }), _jsxs("section", { className: "bg-gray-50 p-3 rounded-md", children: [_jsx("h4", { className: "font-medium mb-1", children: "Contacto para soporte y renovaciones:" }), _jsxs("p", { className: "text-sm text-gray-600", children: ["WhatsApp: +591 73099696", _jsx("br", {}), "Email: soporte@inventorysuit.com"] })] }), _jsx("div", { className: "flex justify-end", children: _jsx(DialogClose, { asChild: true, children: _jsx(Button, { className: "bg-blue-600 hover:bg-blue-700 text-white", children: "Entendido" }) }) })] })] })] }));
};
export default SubscriptionHelpButton;
