import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import { Button } from '../components/ui/button';
const SubscriptionExpired = () => {
    const { subscription } = useAuth();
    const navigate = useNavigate();
    return (_jsx("div", { className: "min-h-screen flex items-center justify-center bg-gray-100", children: _jsxs("div", { className: "max-w-md w-full space-y-8 p-10 bg-white rounded-xl shadow-lg", children: [_jsxs("div", { className: "text-center", children: [_jsx("h1", { className: "text-3xl font-bold text-red-600", children: "Suscripci\u00F3n vencida" }), _jsx("div", { className: "mt-4", children: _jsx("svg", { className: "mx-auto h-16 w-16 text-red-500", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" }) }) }), _jsx("p", { className: "mt-4 text-lg text-gray-600", children: "Tu suscripci\u00F3n ha expirado. Para continuar usando InventorySuit, necesitas renovar tu plan." }), subscription?.endDate && (_jsxs("p", { className: "mt-2 text-sm text-gray-500", children: ["Expir\u00F3 el ", new Date(subscription.endDate).toLocaleDateString()] })), _jsxs("div", { className: "mt-6 bg-gray-50 p-4 rounded-lg border border-gray-200", children: [_jsx("p", { className: "text-sm text-gray-700 mb-2 font-medium", children: "Plan actual: Mensual" }), _jsx("p", { className: "text-sm text-gray-600", children: "Bs. 280 / mes" }), _jsxs("ul", { className: "mt-3 text-xs text-gray-500 space-y-1 text-left", children: [_jsx("li", { children: "\u2022 Gesti\u00F3n completa de inventario" }), _jsx("li", { children: "\u2022 Reportes detallados" }), _jsx("li", { children: "\u2022 M\u00FAltiples almacenes" }), _jsx("li", { children: "\u2022 Soporte prioritario" })] })] })] }), _jsxs("div", { className: "mt-8", children: [_jsx(Button, { onClick: () => navigate('/subscription/renew'), className: "w-full bg-blue-600 hover:bg-blue-700 text-white", children: "Renovar suscripci\u00F3n" }), _jsx(Button, { onClick: () => window.open('https://wa.me/59173099696?text=Necesito%20renovar%20mi%20suscripci%C3%B3n%20a%20InventorySuit', '_blank'), className: "w-full mt-2 bg-green-600 hover:bg-green-700 text-white", children: "Contactar soporte" })] })] }) }));
};
export default SubscriptionExpired;
