name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Build application
        run: npm run build

      - name: Build preload script
        run: npm run build:preload

      - name: Test build with electron-forge
        run: npm run make:win

      - name: List build artifacts
        run: |
          echo "Build artifacts:"
          dir out\make\squirrel.windows\x64

      - name: Upload build artifacts (manual or [artifacts] only)
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, '[artifacts]'))
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: windows-installer-${{ github.sha }}
          path: out/make/squirrel.windows/x64/*.exe
          retention-days: 7